### ISSUE TITLE
Request for detailed docs on how to configure iptables

### ISSUE THREAD

**Issue by saurabhnanda** [kravietz/ansible-ipsec#7]
Are the instructions given at https://github.com/kravietz/ansible-ipsec/blob/fb98a4ff5219dcc709aa411f68d00665142069de/README.md#firewall applicable to both modes, `ike` and `setkey`, or only the former?

If one is using `setkey` is `iptables -A INPUT -p esp -j ACCEPT` still required?

**Comment by kravietz** [comment]
@saurabhnanda good point, just added these!
